### ISSUE TITLE
Provide line marker info for advised methods/properties

### ISSUE THREAD

**Issue by lisachenko** [goaop/idea-plugin#1]
Most wanted feature for framework plugin should be analysis of pointcuts and joinpoints in runtime and providing a markers with ability to go to/from advised class/advisor. Something like icon on the gutter, but for advices and matching joinpoints:

![inheritance-php](https://cloud.githubusercontent.com/assets/640114/7863162/4c1da54c-0563-11e5-8222-42b68caa7bfc.png)

List of issues to resolve before this one:
- [x] #2 PSI helper to create a matcher for PhpNamedElement
- [x] #3 Index for all pointcut expressions in the project
- [x] #4 Implement all general pointcut class for IDEA

**Comment by lisachenko** [comment]
Examples from IDEA and Spring aspects:

Navigation from advices to the advised joinpoints:
![spring-aspect-marker](https://cloud.githubusercontent.com/assets/640114/7864546/70665090-056b-11e5-8e11-b5e150b19967.png)

Navigation from joinpoints to the advices:
![spring-class-marker](https://cloud.githubusercontent.com/assets/640114/7864547/70832c4c-056b-11e5-8d62-4a95ce357fc7.png)

**Comment by lisachenko** [comment]
Done, but now navigation only works from advised elements to the advices. Resolving elements for advices is too expensive for now. Need to think about this more.

**Comment by lisachenko** [comment]
Here is a gif with working navigation :)

![advise-navigation](https://cloud.githubusercontent.com/assets/640114/14080644/2231a3a4-f50f-11e5-8ade-2c9746fbd0e7.gif)

**Comment by TheCelavi** [comment]
Shoud this feature display ALL advised methods/properties?

I have 4 classes with 6 advised method per each class (24 in total). Only 6 from first class are displayed in the list.

**Comment by lisachenko** [comment]
@TheCelavi your question is related more to the #5. And previously everything was working, so yes. There should be 24 methods to navigate to from the one single aspect advice.
But, still have question: are your classes in the same directory or not? (Maybe you use some of them from vendor classes?)

**Comment by TheCelavi** [comment]
All 4 classes are in same directory, non of those classes are in vendor directory.
